spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/clever_bank
    username: enter your username
    password: enter your password
percentageScheduler:
  monthPercentage: 1.0
  initialDelay: 10000 # 110 seconds
  fixedRate: 30000 # 30 seconds
BYNScheduler:
  url: https://api.nbrb.by/exrates/rates/
  initialDelay: 6000 # 6 seconds
  fixedRate: 3600000 # 1hour
schedulers:
  enabled: true
