###пополнения и снятия средств со счета
POST http://localhost:8080/transactions/change
Content-Type: application/json

{
  "account_sender_id": "FUCB OY0M VHZ4 U8Y6 11DQ RQ3Y 5T62",
  "account_recipient_id": "55JN NKDA XKNN Z0QV 5LGL FXF7 XJT9",
  "sum": 255,
  "type": "REPLENISHMENT"
}

###перевод с одного счёта на другой
POST http://localhost:8080/transactions/transfer
Content-Type: application/json

{
  "account_sender_id": "FUCB OY0M VHZ4 U8Y6 11DQ RQ3Y 5T62",
  "account_recipient_id": "ZMEJ L8W1 YNCU JRK6 XOYG Z4R1 IDIJ",
  "sum": 20
}

###перевод с одного счёта на другой с обменом валют по курсу НБ РБ
POST http://localhost:8080/transactions/exchange
Content-Type: application/json

{
  "account_sender_id": "G5QZ 6B43 A6XG AHNK CO6S PSO6 718Q",
  "account_recipient_id": "FUCB OY0M VHZ4 U8Y6 11DQ RQ3Y 5T62",
  "sum": 10
}

###формирования выписки по транзакциям пользователя за период времени
POST http://localhost:8080/transactions/statement
Content-Type: application/json

{
  "from": "2023-09-20",
  "to": "2023-09-20",
  "account_id": "FUCB OY0M VHZ4 U8Y6 11DQ RQ3Y 5T62"
}

###информация о количестве потраченных и полученных средств за период времени
POST http://localhost:8080/transactions/amount
Content-Type: application/json

{
  "from": "2023-09-20",
  "to": "2023-09-20",
  "account_id": "G5QZ 6B43 A6XG AHNK CO6S PSO6 718Q"
}

###найти транзакцию по id
GET http://localhost:8080/transactions/2
Accept: application/json

###найти все транзакции по account_sender_id
GET http://localhost:8080/transactions/senders/G5QZ 6B43 A6XG AHNK CO6S PSO6 718Q
Accept: application/json

###найти все транзакции по account_recipient_id
GET http://localhost:8080/transactions/recipients/0J2O 6O3P 1CUB VZUT 91SJ X3FU MUR4
Accept: application/json
